### ISSUE TITLE
GEO instances should truncate values

### ISSUE THREAD

**Issue by rafaelmartinelli** [matago/TSPLIB.jl#13]
Currently, the package is rounding the calculated distances for `GEO` instances. Following the description on [the documentation](http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp95.pdf), the distances should be truncated.

For example, instance `ulysses16` has distance 1.0 for every arc (i, i), and the optimal value found is 6867.0 instead of 6859.0.

**Comment by rafaelmartinelli** [comment]
I've already fixed this. I'll create a pull request.

**Comment by nathanPro** [comment]
Hello everyone!

I have the impression that the current implementation does not match what TSPlib describes in the documentation.

In particular, the documentation states that, when computing the latitude and longitude in radians, we need to do:

> deg = nint( y[i])

and then, when computing the distances, we need to do

> dij = (int) ( RRR * acos( 0.5*((1.0+q1)*q2 - (1.0-q1)*q3) ) + 1.0);

If I am not confusing the conversion between C and Julia, this amounts to using `round` in the first part, and `trunc` in the second.
The current implementation uses `trunc` in both:

https://github.com/matago/TSPLIB.jl/blob/6f7757427a808806b1879b90fa6713f254ad4a01/src/distances.jl#L77

https://github.com/matago/TSPLIB.jl/blob/6f7757427a808806b1879b90fa6713f254ad4a01/src/distances.jl#L89

Honestly this is more consistent, but I wonder if it changes the graphs computed from the data.
I do not know if this change instances; I am comparing some experiments with code that uses this library, so I used `static_cast<int>` in both cases.

I guess my main question is: am I missing something? Have you guys noted that TSPlib uses both `round` and `trunc` and deliberately chose the current implementation?
