### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by rafaelmartinelli** [matago/TSPLIB.jl#15]
Can we have a new release? I'm using the package in a course.
Thanks for the package, @matago, I started doing other packages inspired in yours.
And thanks @chkwon for the book.

**Comment by chkwon** [comment]
@rafaelmartinelli Thanks for reading my book! :)

@matago I just made a pull request for a new version. Once it is merged, I think I can help with registering the new version.

**Comment by matago** [comment]
@chkwon PR is merged.  Thanks for the assistance.

**Comment by chkwon** [comment]
@rafaelmartinelli  A new version is released. `v0.1.1`
