### ISSUE TITLE
Computing a different weight type

### ISSUE THREAD

**Issue by rocarvaj** [matago/TSPLIB.jl#2]
Hello! First of all thanks for this package.
I'm reading a TSPLIB instances using the `readTSPLIB` function, say `gr120`. I want to use the euclidean distances for this instance, but the .tsp file states that the weights given are of type "EXPLICIT". I thought: "I'll just use the `calc_weight` function in `reader.jl`", but since this function is not exported in `TSPLIB.jl`, I could not use it.
I guess that you can always make a copy of the .tsp file and just change the `EDGE_WEIGHT_TYPE` and read that file, but I would be nice to be able to change the weight type after reading the file.

Just a suggestion.

Thanks!

**Comment by chkwon** [comment]
Have you tried

```Julia
using TSPLIB
TSPLIB.calc_weights ...
```

**Comment by rafaelmartinelli** [comment]
Do we still need this?

**Comment by matago** [comment]
@rocarvaj Does the suggestion from @chkwon work for you?  If no response I will close this issue.

**Comment by rocarvaj** [comment]
> Have you tried
> 
> ```julia
> using TSPLIB
> TSPLIB.calc_weights ...
> ```

Hi! Sorry for not replying to this. This works indeed. Thanks for the help!
